spring.application.name=StoryBook
server.port = 1234
spring.datasource.url = jdbc:mysql://localhost:3306/storybookdb
spring.datasource.username = root
spring.datasource.password = ArPaN@5678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto = update

spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Enable debug logging for troubleshooting
# logging.level.org.springframework=DEBUG
# logging.level.com.company.storybook=DEBUG

